import type { Book } from "@/types/book";

export const mockBooks: Book[] = [
  {
    id: 1,
    title: "Cien años de soledad",
    isbn: "978-0307474728",
    description:
      "La saga de la familia Buendía a lo largo de siete generaciones en el mítico pueblo de Macondo, una obra cumbre del realismo mágico latinoamericano.",
    editorial: "Editorial Sudamericana",
    publicationDate: "1967-05-30",
    coverUrl: "https://picsum.photos/seed/cien-anos/400/600",
    language: "Español",
    authors: ["Gabriel García Márquez"],
    categories: ["Novela", "Realismo mágico"],
    pageCount: 471,
  },
  {
    id: 2,
    title: "Don Quijote de la Mancha",
    isbn: "978-8420412146",
    description:
      "Las desventuras del ingenioso hidalgo y su fiel escudero Sancho Panza, considerada una de las obras más influyentes de la literatura universal.",
    editorial: "Alfaguara",
    publicationDate: "1605-01-16",
    coverUrl: "https://picsum.photos/seed/quijote/400/600",
    language: "Español",
    authors: ["Miguel de Cervantes"],
    categories: ["Clásico", "Aventura"],
    pageCount: 1376,
  },
  {
    id: 3,
    title: "1984",
    isbn: "978-0451524935",
    description:
      "Una distopía sobre un régimen totalitario que controla cada aspecto de la vida de sus ciudadanos a través de la vigilancia y la manipulación del lenguaje.",
    editorial: "Secker & Warburg",
    publicationDate: "1949-06-08",
    coverUrl: "https://picsum.photos/seed/1984/400/600",
    language: "Inglés",
    authors: ["George Orwell"],
    categories: ["Distopía", "Ciencia ficción"],
    pageCount: 328,
  },
  {
    id: 4,
    title: "El nombre del viento",
    isbn: "978-8401352836",
    description:
      "La historia narrada por Kvothe, un legendario músico, mago y aventurero, sobre cómo se convirtió en el hombre del que todos hablan.",
    editorial: "Plaza & Janés",
    publicationDate: "2007-03-27",
    coverUrl: "https://picsum.photos/seed/nombre-viento/400/600",
    language: "Español",
    authors: ["Patrick Rothfuss"],
    categories: ["Fantasía", "Aventura"],
    pageCount: 880,
  },
  {
    id: 5,
    title: "Sapiens: De animales a dioses",
    isbn: "978-8499926223",
    description:
      "Un recorrido por la historia de la humanidad desde la aparición del Homo sapiens hasta las revoluciones que han moldeado el mundo moderno.",
    editorial: "Debate",
    publicationDate: "2014-09-04",
    coverUrl: "https://picsum.photos/seed/sapiens/400/600",
    language: "Español",
    authors: ["Yuval Noah Harari"],
    categories: ["Historia", "Ensayo"],
    pageCount: 496,
  },
  {
    id: 6,
    title: "El Hobbit",
    isbn: "978-8445073803",
    description:
      "Bilbo Bolsón se embarca en una aventura inesperada junto a un grupo de enanos y el mago Gandalf para recuperar un tesoro custodiado por el dragón Smaug.",
    editorial: "Minotauro",
    publicationDate: "1937-09-21",
    coverUrl: "https://picsum.photos/seed/hobbit/400/600",
    language: "Español",
    authors: ["J.R.R. Tolkien"],
    categories: ["Fantasía", "Clásico"],
    pageCount: 320,
  },
  {
    id: 7,
    title: "Crónica de una muerte anunciada",
    isbn: "978-0307387264",
    description:
      "La reconstrucción de un asesinato que todos en el pueblo sabían que iba a ocurrir, salvo la víctima. Una novela corta sobre el destino y el honor.",
    editorial: "Editorial La Oveja Negra",
    publicationDate: "1981-04-01",
    coverUrl: "https://picsum.photos/seed/cronica/400/600",
    language: "Español",
    authors: ["Gabriel García Márquez"],
    categories: ["Novela", "Drama"],
    pageCount: 122,
  },
  {
    id: 8,
    title: "Clean Code",
    isbn: "978-0132350884",
    description:
      "Una guía práctica sobre cómo escribir código limpio, mantenible y legible, con principios y prácticas aplicables a cualquier lenguaje de programación.",
    editorial: "Prentice Hall",
    publicationDate: "2008-08-01",
    coverUrl: "https://picsum.photos/seed/clean-code/400/600",
    language: "Inglés",
    authors: ["Robert C. Martin"],
    categories: ["Tecnología", "Programación"],
    pageCount: 464,
  },
  {
    id: 9,
    title: "Rayuela",
    isbn: "978-8437604572",
    description:
      "Una novela experimental que puede leerse de múltiples maneras, donde Horacio Oliveira busca un sentido a su vida entre París y Buenos Aires.",
    editorial: "Cátedra",
    publicationDate: "1963-06-28",
    coverUrl: "https://picsum.photos/seed/rayuela/400/600",
    language: "Español",
    authors: ["Julio Cortázar"],
    categories: ["Novela", "Experimental"],
    pageCount: 736,
  },
  {
    id: 10,
    title: "Dune",
    isbn: "978-0441172719",
    description:
      "En el desértico planeta Arrakis, el joven Paul Atreides debe enfrentar fuerzas políticas, religiosas y ecológicas que decidirán el destino del universo.",
    editorial: "Chilton Books",
    publicationDate: "1965-08-01",
    coverUrl: "https://picsum.photos/seed/dune/400/600",
    language: "Inglés",
    authors: ["Frank Herbert"],
    categories: ["Ciencia ficción", "Aventura"],
    pageCount: 688,
  },
  {
    id: 11,
    title: "Orgullo y prejuicio",
    isbn: "978-0141439518",
    description:
      "Elizabeth Bennet y el señor Darcy protagonizan una de las historias de amor más célebres de la literatura inglesa, en una crítica a la sociedad de su época.",
    editorial: "T. Egerton",
    publicationDate: "1813-01-28",
    coverUrl: "https://picsum.photos/seed/orgullo/400/600",
    language: "Inglés",
    authors: ["Jane Austen"],
    categories: ["Romance", "Clásico"],
    pageCount: 432,
  },
  {
    id: 12,
    title: "El principito",
    isbn: "978-0156012195",
    description:
      "Un piloto perdido en el desierto encuentra a un pequeño príncipe que viene de otro planeta. Una fábula poética sobre la infancia, la amistad y la pérdida.",
    editorial: "Reynal & Hitchcock",
    publicationDate: "1943-04-06",
    coverUrl: "https://picsum.photos/seed/principito/400/600",
    language: "Francés",
    authors: ["Antoine de Saint-Exupéry"],
    categories: ["Fábula", "Clásico"],
    pageCount: 96,
  },
];
